[2024-05-06 05:11:24,065] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_scoring_training_pipeline.training_model manual__2024-05-06T05:11:11.138944+00:00 [queued]>
[2024-05-06 05:11:24,070] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_scoring_training_pipeline.training_model manual__2024-05-06T05:11:11.138944+00:00 [queued]>
[2024-05-06 05:11:24,070] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-05-06 05:11:24,070] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2024-05-06 05:11:24,070] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-05-06 05:11:24,091] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): training_model> on 2024-05-06 05:11:11.138944+00:00
[2024-05-06 05:11:24,098] {standard_task_runner.py:52} INFO - Started process 4080 to run task
[2024-05-06 05:11:24,101] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Lead_scoring_training_pipeline', 'training_model', 'manual__2024-05-06T05:11:11.138944+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/Lead_scoring_training_pipeline/.ipynb_checkpoints/lead_scoring_training_pipeline-checkpoint.py', '--cfg-path', '/tmp/tmpw3zwq8ba', '--error-file', '/tmp/tmp508sr7e0']
[2024-05-06 05:11:24,101] {standard_task_runner.py:80} INFO - Job 50: Subtask training_model
[2024-05-06 05:11:24,145] {task_command.py:371} INFO - Running <TaskInstance: Lead_scoring_training_pipeline.training_model manual__2024-05-06T05:11:11.138944+00:00 [running]> on host 9eefda8bbe39
[2024-05-06 05:11:24,216] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Lead_scoring_training_pipeline
AIRFLOW_CTX_TASK_ID=training_model
AIRFLOW_CTX_EXECUTION_DATE=2024-05-06T05:11:11.138944+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-06T05:11:11.138944+00:00
[2024-05-06 05:11:28,288] {utils.py:115} INFO - creating mlflow experiment
[2024-05-06 05:11:28,794] {utils.py:119} INFO - setting mlflow experiment
[2024-05-06 05:11:28,958] {logging_mixin.py:115} WARNING - /opt/conda/lib/python3.8/site-packages/sklearn/utils/validation.py:72 DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
[2024-05-06 05:11:33,064] {logging_mixin.py:115} WARNING - Registered model 'LightGBM' already exists. Creating a new version of this model...
[2024-05-06 05:11:33,219] {logging_mixin.py:115} WARNING - 2024/05/06 05:11:33 INFO mlflow.tracking._model_registry.client: Waiting up to 300 seconds for model version to finish creation.                     Model name: LightGBM, version 4
[2024-05-06 05:11:33,219] {logging_mixin.py:115} WARNING - Created version '4' of model 'LightGBM'.
[2024-05-06 05:11:33,904] {logging_mixin.py:115} INFO - Inside MLflow Run with id b1645b3347414b2ea0346ef1e22a2cd3
[2024-05-06 05:11:33,930] {python.py:173} INFO - Done. Returned value was: None
[2024-05-06 05:11:33,936] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=Lead_scoring_training_pipeline, task_id=training_model, execution_date=20240506T051111, start_date=20240506T051124, end_date=20240506T051133
[2024-05-06 05:11:33,985] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-05-06 05:11:34,012] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
