[2024-05-06 04:57:17,311] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_scoring_training_pipeline.encoding_categorical_variables scheduled__2024-05-05T00:00:00+00:00 [queued]>
[2024-05-06 04:57:17,316] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_scoring_training_pipeline.encoding_categorical_variables scheduled__2024-05-05T00:00:00+00:00 [queued]>
[2024-05-06 04:57:17,316] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-05-06 04:57:17,316] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2024-05-06 04:57:17,316] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-05-06 04:57:17,335] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): encoding_categorical_variables> on 2024-05-05 00:00:00+00:00
[2024-05-06 04:57:17,343] {standard_task_runner.py:52} INFO - Started process 2287 to run task
[2024-05-06 04:57:17,346] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Lead_scoring_training_pipeline', 'encoding_categorical_variables', 'scheduled__2024-05-05T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/Lead_scoring_training_pipeline/lead_scoring_training_pipeline.py', '--cfg-path', '/tmp/tmpsroncqm1', '--error-file', '/tmp/tmpczb8bd6y']
[2024-05-06 04:57:17,346] {standard_task_runner.py:80} INFO - Job 20: Subtask encoding_categorical_variables
[2024-05-06 04:57:17,387] {task_command.py:371} INFO - Running <TaskInstance: Lead_scoring_training_pipeline.encoding_categorical_variables scheduled__2024-05-05T00:00:00+00:00 [running]> on host 9eefda8bbe39
[2024-05-06 04:57:17,464] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Lead_scoring_training_pipeline
AIRFLOW_CTX_TASK_ID=encoding_categorical_variables
AIRFLOW_CTX_EXECUTION_DATE=2024-05-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-05T00:00:00+00:00
[2024-05-06 04:57:17,465] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/dags/Lead_scoring_training_pipeline/utils.py", line 56, in encode_features
    conn = sqlite3.connect(DB_PATH+DB_FILE_NAME)
sqlite3.OperationalError: unable to open database file
[2024-05-06 04:57:17,468] {taskinstance.py:1415} INFO - Marking task as UP_FOR_RETRY. dag_id=Lead_scoring_training_pipeline, task_id=encoding_categorical_variables, execution_date=20240505T000000, start_date=20240506T045717, end_date=20240506T045717
[2024-05-06 04:57:17,484] {standard_task_runner.py:92} ERROR - Failed to execute job 20 for task encoding_categorical_variables (unable to open database file; 2287)
[2024-05-06 04:57:17,517] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-05-06 04:57:17,554] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
