[2024-05-06 04:57:26,540] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_scoring_training_pipeline.encoding_categorical_variables scheduled__2024-05-05T00:00:00+00:00 [queued]>
[2024-05-06 04:57:26,545] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_scoring_training_pipeline.encoding_categorical_variables scheduled__2024-05-05T00:00:00+00:00 [queued]>
[2024-05-06 04:57:26,545] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-05-06 04:57:26,545] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2024-05-06 04:57:26,545] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-05-06 04:57:26,564] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): encoding_categorical_variables> on 2024-05-05 00:00:00+00:00
[2024-05-06 04:57:26,572] {standard_task_runner.py:52} INFO - Started process 2324 to run task
[2024-05-06 04:57:26,575] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Lead_scoring_training_pipeline', 'encoding_categorical_variables', 'scheduled__2024-05-05T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/Lead_scoring_training_pipeline/lead_scoring_training_pipeline.py', '--cfg-path', '/tmp/tmpsvzyon1h', '--error-file', '/tmp/tmp50aag4wv']
[2024-05-06 04:57:26,576] {standard_task_runner.py:80} INFO - Job 22: Subtask encoding_categorical_variables
[2024-05-06 04:57:26,617] {task_command.py:371} INFO - Running <TaskInstance: Lead_scoring_training_pipeline.encoding_categorical_variables scheduled__2024-05-05T00:00:00+00:00 [running]> on host 9eefda8bbe39
[2024-05-06 04:57:26,659] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Lead_scoring_training_pipeline
AIRFLOW_CTX_TASK_ID=encoding_categorical_variables
AIRFLOW_CTX_EXECUTION_DATE=2024-05-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-05T00:00:00+00:00
[2024-05-06 04:57:26,660] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/dags/Lead_scoring_training_pipeline/utils.py", line 56, in encode_features
    conn = sqlite3.connect(DB_PATH+DB_FILE_NAME)
sqlite3.OperationalError: unable to open database file
[2024-05-06 04:57:26,663] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=Lead_scoring_training_pipeline, task_id=encoding_categorical_variables, execution_date=20240505T000000, start_date=20240506T045726, end_date=20240506T045726
[2024-05-06 04:57:26,682] {standard_task_runner.py:92} ERROR - Failed to execute job 22 for task encoding_categorical_variables (unable to open database file; 2324)
[2024-05-06 04:57:26,706] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-05-06 04:57:26,751] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
